[package]
name = "tob"
version = "0.1.0"
authors = ["mramirez <ramirezmike2@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.24"
quote = "1.0.9"
syn = { version="1.0.61", features = ["full", "extra-traits"] }
